#!/usr/bin/env python3

"""
Copy a Spotify playlist to a YTMusic playlist
"""

import sys
import json
from ytmusicapi import YTMusic
from icecream import ic


if len(sys.argv) != 3:
    print(f"usage: {sys.argv[0]} <SPOTIFY PLAYLIST ID> <YOUTUBE PLAYLIST ID>")
    sys.exit(1)

src_pl_id = sys.argv[1]
dst_pl_id = sys.argv[2]

yt = YTMusic("oauth.json")


def lookup_song(yt, track_name, artist_name, album_name):
    # for pl in playlists:
    #    print(f"{pl['playlistId']} {pl['title']}")

    albums = yt.search(query=f"{album_name} by {artist_name}", filter="albums")
    for album in albums[:3]:
        # print(album)
        # print(f"ALBUM: {album['browseId']} - {album['title']} - {album['artists'][0]['name']}")

        for track in yt.get_album(album["browseId"])["tracks"]:
            if track["title"] == track_name:
                return track
            # print(f"{track['videoId']} - {track['title']} - {track['artists'][0]['name']}")

    songs = yt.search(query=f"{track_name} by {artist_name}", filter="songs")
    return songs[0]

    #  This would need to do fuzzy matching
    for song in songs:
        if (
            song["title"] == track_name
            and song["artists"][0]["name"] == artist_name
            and song["album"]["name"] == album_name
        ):
            return song
        # print(f"SONG: {song['videoId']} - {song['title']} - {song['artists'][0]['name']} - {song['album']['name']}")

    raise ValueError(f"Did not find {track_name} by {artist_name} from {album_name}")


spotify_pls = json.load(open("playlists.json", "r"))
yt_pl = yt.get_playlist(playlistId=dst_pl_id)
print(f"== Youtube Playlist: {yt_pl['title']}")

for src_pl in spotify_pls["playlists"]:
    if src_pl.get("id") != src_pl_id:
        continue

    src_pl_name = src_pl["name"]

    print(f"== Spotify Playlist: {src_pl_name}")

    for src_track in src_pl["tracks"]:
        src_album_artist = src_track["track"]["album"]["artists"][0]["name"]
        src_album_name = src_track["track"]["album"]["name"]
        src_track_artist = src_track["track"]["artists"][0]["name"]
        src_track_name = src_track["track"]["name"]

        print(f"Spotify:   {src_track_name} - {src_track_artist} - {src_album_name}")
        dst_track = lookup_song(yt, src_track_name, src_track_artist, src_album_name)
        # print(f"  Youtube: {dst_track['videoId']} - {dst_track['title']} - {dst_track['artists'][0]['name']}")
        print(
            f"  Youtube: {dst_track['title']} - {dst_track['artists'][0]['name']} - {dst_track['album']}"
        )

        yt.add_playlist_items(
            playlistId=dst_pl_id, videoIds=[dst_track["videoId"]], duplicates=False
        )
