#!/usr/bin/env python3

"""
Copy a Spotify playlist to a YTMusic playlist
"""

import sys
import json
import time
from argparse import ArgumentParser
from ytmusicapi import YTMusic


def lookup_song(yt, track_name, artist_name, album_name):
    # for pl in playlists:
    #    print(f"{pl['playlistId']} {pl['title']}")

    albums = yt.search(query=f"{album_name} by {artist_name}", filter="albums")
    for album in albums[:3]:
        # print(album)
        # print(f"ALBUM: {album['browseId']} - {album['title']} - {album['artists'][0]['name']}")

        for track in yt.get_album(album["browseId"])["tracks"]:
            if track["title"] == track_name:
                return track
            # print(f"{track['videoId']} - {track['title']} - {track['artists'][0]['name']}")

    songs = yt.search(query=f"{track_name} by {artist_name}", filter="songs")
    return songs[0]

    #  This would need to do fuzzy matching
    for song in songs:
        if (
            song["title"] == track_name
            and song["artists"][0]["name"] == artist_name
            and song["album"]["name"] == album_name
        ):
            return song
        # print(f"SONG: {song['videoId']} - {song['title']} - {song['artists'][0]['name']} - {song['album']['name']}")

    raise ValueError(f"Did not find {track_name} by {artist_name} from {album_name}")


def parse_arguments():
    parser = ArgumentParser()
    parser.add_argument(
        "--track-sleep",
        type=float,
        default=0.1,
        help="Time to sleep between each track that is added (default: 0.1)",
    )
    parser.add_argument(
        "spotify_playlist_id", type=str, help="ID of the Spotify playlist to copy from"
    )
    parser.add_argument(
        "ytmusic_playlist_id", type=str, help="ID of the YTMusic playlist to copy to"
    )

    return parser.parse_args()


args = parse_arguments()

src_pl_id = args.spotify_playlist_id
dst_pl_id = args.ytmusic_playlist_id

yt = YTMusic("oauth.json")

spotify_pls = json.load(open("playlists.json", "r"))
yt_pl = yt.get_playlist(playlistId=dst_pl_id)
print(f"== Youtube Playlist: {yt_pl['title']}")

for src_pl in spotify_pls["playlists"]:
    if src_pl.get("id") != src_pl_id:
        continue

    src_pl_name = src_pl["name"]

    print(f"== Spotify Playlist: {src_pl_name}")

    for src_track in src_pl["tracks"]:
        src_album_artist = src_track["track"]["album"]["artists"][0]["name"]
        src_album_name = src_track["track"]["album"]["name"]
        src_track_artist = src_track["track"]["artists"][0]["name"]
        src_track_name = src_track["track"]["name"]

        print(f"Spotify:   {src_track_name} - {src_track_artist} - {src_album_name}")
        dst_track = lookup_song(yt, src_track_name, src_track_artist, src_album_name)
        # print(f"  Youtube: {dst_track['videoId']} - {dst_track['title']} - {dst_track['artists'][0]['name']}")
        print(
            f"  Youtube: {dst_track['title']} - {dst_track['artists'][0]['name']} - {dst_track['album']}"
        )

        exception_sleep = 5
        for x in range(10):
            try:
                yt.add_playlist_items(
                    playlistId=dst_pl_id,
                    videoIds=[dst_track["videoId"]],
                    duplicates=False,
                )
                break
            except Exception as e:
                print(f"ERROR: (Retrying) {e} in {exception_sleep} seconds")
                time.sleep(exception_sleep)
                exception_sleep *= 2

        if args.track_sleep:
            time.sleep(args.track_sleep)
