#!/usr/bin/env python3

"""
List the playlists on Spotify and YTMusic
"""

import json
from ytmusicapi import YTMusic

yt = YTMusic("oauth.json")


spotify_pls = json.load(open("playlists.json", "r"))

#  Liked music
print('== Spotify')
for src_pl in spotify_pls["playlists"]:
    print(f"{src_pl.get('id')} - {src_pl['name']:50} ({len(src_pl['tracks'])} tracks)")

print()
print('== YTMusic')
for pl in yt.get_library_playlists(limit=5000):
    print(f"{pl['playlistId']} - {pl['title']:40} ({pl.get('count', '?')} tracks)")
